version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "8080:8080" # Server exposed port
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "3005:80" # React client exposed port
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
