# version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    pull_policy: build
    environment:
      - SERVER_PORT=${SERVER_PORT:-8082}
      - SOCKET_SERVER_URL=${SOCKET_SERVER_URL}
    ports:
      - "${SERVER_PORT:-8082}:${SERVER_PORT:-8082}"
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    pull_policy: build
    environment:
      - REACT_APP_SOCKET_SERVER_URL=${REACT_APP_SOCKET_SERVER_URL}
      - CLIENT_PORT=${CLIENT_PORT:-3005}
    ports:
      - "${CLIENT_PORT}:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
